
package jvra.com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import jvra.com.types.ClientType;
import jvra.com.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bank", targetNamespace = "http://com.jvra/port")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bank {


    /**
     * 
     * @param client
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "userHasAccountResponse", targetNamespace = "http://com.jvra/types", partName = "return")
    @Action(input = "http://com.jvra/port/userHasAccount", output = "http://com.jvra/port/hasAccountResponse")
    public boolean userHasAccount(
        @WebParam(name = "client", targetNamespace = "http://com.jvra/types", partName = "client")
        ClientType client);

}
